In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Raw Dataset/Movies.csv")

In [3]:
# First 5 Rows
df.head()

,budget,revenue,popularity,runtime,vote_average,title,genres
0,57755036,107323371,60.377360,98,6.611888,Movie 1,"[{'id': 10749, 'name': 'Romance'}]"
1,192100010,342896533,86.289857,96,7.184687,Movie 2,"[{'id': 18, 'name': 'Drama'}]"
2,128521863,253206827,86.995324,148,3.542978,Movie 3,"[{'id': 35, 'name': 'Comedy'}]"
3,156299516,89635602,72.710096,118,5.985176,Movie 4,"[{'id': 18, 'name': 'Drama'}]"
4,148532820,221133868,74.829585,161,4.578480,Movie 5,"[{'id': 35, 'name': 'Comedy'}]"

In [4]:
print("Shape:", df.shape)

df.info()

df.describe(include="all")

Shape: (2000, 7)
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   budget        2000 non-null   int64
 1   revenue       2000 non-null   int64
 2   popularity    2000 non-null   float64
 3   runtime       2000 non-null   int64
 4   vote_average  2000 non-null   float64
 5   title         2000 non-null   str
 6   genres        2000 non-null   str
dtypes: float64(2), int64(3), str(2)
memory usage: 109.5 KB

,budget,revenue,popularity,runtime,vote_average,title,genres
count,2.000000e+03,2.000000e+03,2000.000000,2000.000000,2000.000000,2000,2000
unique,NaN,NaN,NaN,NaN,NaN,2000,10
top,NaN,NaN,NaN,NaN,NaN,Movie 1,"[{'id': 10749, 'name': 'Romance'}]"
freq,NaN,NaN,NaN,NaN,NaN,1,220
mean,1.019211e+08,1.780574e+08,50.090738,129.568000,6.036764,NaN,NaN
std,5.682795e+07,1.293879e+08,28.482104,28.906507,1.743093,NaN,NaN
min,1.070640e+06,1.138729e+06,1.018466,80.000000,3.008133,NaN,NaN
25%,5.274832e+07,7.458306e+07,25.720784,104.000000,4.583298,NaN,NaN
50%,1.026023e+08,1.484882e+08,50.210396,130.000000,6.052901,NaN,NaN
75%,1.507962e+08,2.623679e+08,74.925354,155.000000,7.577305,NaN,NaN
max,1.999879e+08,5.744901e+08,99.764659,179.000000,8.998509,NaN,NaN

In [5]:
# Missing Values

df.isnull().sum()

budget          0
revenue         0
popularity      0
runtime         0
vote_average    0
title           0
genres          0
dtype: int64

In [6]:
# Duplicate Records

df.duplicated().sum()

np.int64(0)

In [7]:
print("Budget = 0 :", (df["budget"] == 0).sum())

print("Revenue = 0 :", (df["revenue"] == 0).sum())

print("Runtime = 0 :", (df["runtime"] == 0).sum())

Budget = 0 : 0
Revenue = 0 : 0
Runtime = 0 : 0

In [8]:
df.columns

Index(['budget', 'revenue', 'popularity', 'runtime', 'vote_average', 'title',
       'genres'],
      dtype='str')

In [9]:
print("Negative Budget :", (df["budget"] < 0).sum())

print("Negative Revenue :", (df["revenue"] < 0).sum())

print("Negative Runtime :", (df["runtime"] < 0).sum())

Negative Budget : 0
Negative Revenue : 0
Negative Runtime : 0

In [10]:
df["title"].duplicated().sum()

np.int64(0)

In [11]:
import ast

In [12]:
def extract_genres(genre_string):
    try:
        genres = ast.literal_eval(genre_string)
        return ", ".join([genre["name"] for genre in genres])
    except:
        return None

In [13]:
[{'id':28,'name':'Action'},
 {'id':12,'name':'Adventure'}]

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}]

In [14]:
df["genres"] = df["genres"].apply(extract_genres)

In [15]:
df[["title", "genres"]].head()

     title   genres
0  Movie 1  Romance
1  Movie 2    Drama
2  Movie 3   Comedy
3  Movie 4    Drama
4  Movie 5   Comedy

In [16]:
df["primary_genre"] = df["genres"].str.split(",").str[0].str.strip()

In [17]:
df[["genres", "primary_genre"]].head(10)

      genres primary_genre
0    Romance       Romance
1      Drama         Drama
2     Comedy        Comedy
3      Drama         Drama
4     Comedy        Comedy
5    Romance       Romance
6  Adventure     Adventure
7     Action        Action
8     Horror        Horror
9     Horror        Horror

In [18]:
# Success = 1 if Revenue > Budget else 0
df["success"] = (df["revenue"] > df["budget"]).astype(int)

df["success"].value_counts()

success
1    1614
0     386
Name: count, dtype: int64

In [19]:
df["profit"] = df["revenue"] - df["budget"]

df[["budget","revenue","profit"]].head()

      budget    revenue     profit
0   57755036  107323371   49568335
1  192100010  342896533  150796523
2  128521863  253206827  124684964
3  156299516   89635602  -66663914
4  148532820  221133868   72601048

In [20]:
df["roi"] = (df["profit"] / df["budget"]) * 100

df[["budget","profit","roi"]].head()

      budget     profit        roi
0   57755036   49568335  85.825130
1  192100010  150796523  78.498967
2  128521863  124684964  97.014594
3  156299516  -66663914 -42.651389
4  148532820   72601048  48.878792

In [21]:
df.head()

,budget,revenue,popularity,runtime,vote_average,title,genres,primary_genre,success,profit,roi
0,57755036,107323371,60.377360,98,6.611888,Movie 1,Romance,Romance,1,49568335,85.825130
1,192100010,342896533,86.289857,96,7.184687,Movie 2,Drama,Drama,1,150796523,78.498967
2,128521863,253206827,86.995324,148,3.542978,Movie 3,Comedy,Comedy,1,124684964,97.014594
3,156299516,89635602,72.710096,118,5.985176,Movie 4,Drama,Drama,0,-66663914,-42.651389
4,148532820,221133868,74.829585,161,4.578480,Movie 5,Comedy,Comedy,1,72601048,48.878792

In [22]:
df.to_csv(
    "Clean Dataset/movies_clean.csv",
    index=False
)

print("✅ Clean dataset exported successfully!")

✅ Clean dataset exported successfully!